### ISSUE TITLE
Is possible to have a more detailed deployment guide?

### ISSUE THREAD

**Issue by toolsofgrit** [adgramigna/job-board-scraper#1]
I think this project is super awesome, but I just have very limited tech knowledge so not very sure how to deploy it from my local environment. Thanks.

**Comment by adgramigna** [comment]
Hi @toolsofgrit I’m glad you’re interested in this project! It is a work in progress right now, but I will definitely add some instructions when I’m finished, I’m guessing within a couple 
months. I will comment in this ticket when it is ready!

**Comment by toolsofgrit** [comment]
Thanks so much. Much appreciated.

**Comment by adgramigna** [comment]
Hi @toolsofgrit, I added some [Local Deployment Instructions](https://github.com/adgramigna/job-board-scraper/blob/5fc37b3d92faeb76a315a0a9de6ddf4e9073b8cc/local_deployment_instructions.md), let me know if this is sufficient. If you have any questions on how to run locally, please reach out!
